struct stat;
struct rtcdate;

// system calls
int fork(void);
int _exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(char*, int);
int mknod(char*, short, short);
int unlink(char*);
int fstat(int fd, struct stat*);
int link(char*, char*);
int mkdir(char*);
int chdir(char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int date(struct rtcdate*);
int dup2(int, int);
int alarm(int, void(*)());
int lseek(int, int, int);

char* strcpy(char*, const char*);
void *memmove(void*, const void*, size_t);
char* strchr(const char*, int c);
int strcmp(const char*, const char*);
size_t strlen(const char*);
void* memset(void*, int, size_t);
int atoi(const char*);
char* xv6_gets(char*, int max);
int xv6_stat(char *, struct stat *);
void xv6_printf(int, char *, ...);
